### ISSUE TITLE
Quartz Block to Nether Quartz

### ISSUE THREAD

**Issue by trzejos** [Classics-Craftworks/Better-Unpackables#2]
### What would you like to see added/changed?

I would like a new recipe for unpacking Nether Quartz. The recipe would be 1 Quartz Block to 4 Nether Quartz.

**Comment by Classsic36** [comment]
Thanks for your suggestion! It will be added in the next beta for v1.2.0.

**Comment by Classsic36** [comment]
Added in [v1.2.0-beta5](https://github.com/Classic36-Media/Better-Unpackables/releases/tag/v1.2.0-beta5). Thanks again!
